########################################################
#### Spring configuration
########################################################
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${public.spring.datasource.url.host}/enc_psdos_rplanmgt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: ${public.spring.datasource.username.host}
    password: ${public.spring.datasource.password.host}
    initial-size: 10
    min-idle: 10
    max-active: 100
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat,wall,log4j
  cloud:
    consul:
      host: ${public.spring.cloud.consul.host}
      port: ${public.spring.cloud.consul.port}
      discovery:
        health-check-critical-timeout: 30s
        prefer-ip-address: true
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false
info:
  security:
    enabled: false

########################################################
#### log configuration
########################################################
logging:
  config: classpath:logback-dev.xml

########################################################
#### 文件服务配置
########################################################
fdfs:
  enabled: ${public.fdfs.enabled}
  # 读取时间
  so-timeout: ${public.fdfs.soTimeout}
  # 连接超时时间
  connect-timeout: ${public.fdfs.connectTimeout}
  # 缩略图
  thumb-image:
    width: ${public.fdfs.thumbImage.width}
    height: ${public.fdfs.thumbImage.height}
  # tracker列表
  tracker-list: ${public.fdfs.trackerList}
  storage-list: ${public.fdfs.storageList}