package com.solan.rules
import com.solan.rules.domain.Product
dialect  "java"
rule "less than 500"
    when
       product: Product( price <100 )
    then
        product.setMessage("价格小于100");
        System.out.println( product );
end
rule "more than 100 and less than 500"
    when
       product: Product( price >= 100 && price < 500)
    then
        product.setMessage("价格在[100, 500)之间");
        System.out.println( product );
end
rule "more than 500"
    when
       product: Product( price >=500 )
    then
        product.setMessage("价格大于100");
        System.out.println( product );
end